FIX: Too many item message and add possibility to change it
Sphereserver/Source-X pull request #567
Opened 2020-12-14 13:33 UTC by Jhobean

When droping an item to the ground and there was too many item, the message was display on the character journal instead of ON the item. It's because the update was not done and your client did not see the item. By putting an Update before, it's fix.

THis part fix the issue like coruja did on #64.

I added the possibility to customize the message by script. For exemple, a french shard don't want to see "Too many items here!"

2020-12-14 15:27 UTC, Nirad commented
Do you need to add this mesage to the other script pack as well to ?

2020-12-14 16:06 UTC, cbnolok commented
As a suggestion, some comments with old code are left there for a reason, it's better to preserve it instead of wiping it

2020-12-14 19:20 UTC, Jhobean commented
@Nirad i have pr old of 1 year on other script pack (56d)   I dont do PR there anymore

2020-12-16 19:51 UTC, cbnolok requested changes

2020-12-16 19:51 UTC, cbnolok commented on src/game/items/CItem.cpp
> +			Speak(g_Cfg.GetDefaultMsg(DEFMSG_TOO_MANY_ITEM));
Can you rename it to DEFMSG_TOO_MANY_ITEMS please?

2020-12-20 19:50 UTC, merged